---
driver:
  name: docker

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: oracle_mio
    driver_config:
      image: oraclelinux:6
      platform: centos

  - name: centos-6.7
    driver_config:
      image: centos:6.7
      platform: centos

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
